# Generated by Django 4.1.3 on 2022-11-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente_info', '0003_alter_paciente_comuna'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ah_pac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_reserva', models.TimeField()),
                ('hora_confirma', models.TimeField()),
                ('online', models.BooleanField()),
                ('link', models.CharField(max_length=800)),
                ('agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda_hora')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente_info.paciente')),
            ],
        ),
    ]
