# Generated by Django 4.1.3 on 2022-11-21 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registar', '0002_alter_especialidad_esp_descripcion'),
        ('ah_paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ah_pac',
            name='psicologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registar.psicologo'),
        ),
        migrations.AddField(
            model_name='ah_pac',
            name='valoracion',
            field=models.IntegerField(null=True),
        ),
    ]
