# Generated by Django 4.1.3 on 2022-12-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ah_paciente', '0002_ah_pac_psicologo_ah_pac_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ah_pac',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ah_pac',
            name='reservada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ah_pac',
            name='hora_confirma',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ah_pac',
            name='hora_reserva',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ah_pac',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
