# Generated by Django 4.1.3 on 2022-11-17 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente_info', '0002_region_comuna_region_paciente_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente_info.comuna'),
        ),
    ]
